library: TF
modeling:
  NET_NAME: GRU-32H1-32H2
paths:
  PATH_TO_EXPERIMENT_FOLDERS: ./SI_Toolkit_ASF/Experiments/
  path_to_experiment: Pretrained-RNN-1/
training_default:
  BATCH_SIZE: 16
  CONSTRUCT_NETWORK: with cells
  EPOCHS: 10
  LR: 0.01
  NORMALIZE: true
  ON_FLY_DATA_GENERATION: false
  POST_WASH_OUT_LEN: 20
  SEED: 1873
  SHIFT_LABELS: 1
  USE_NNI: false
  WASH_OUT_LEN: 10
  control_inputs:
  - Q
  outputs:
  - angle_sin
  - angle_cos
  - angleD
  - position
  - positionD
  setpoint_inputs: []
  state_inputs:
  - angle_sin
  - angle_cos
  - angleD
  - position
  - positionD
  translation_invariant_variables: []
